---
minimum_pre_commit_version: 3.3.2
exclude: ^test-data/

repos:

# pre-commit hooks
# ----------

# Standard pre-commit rules
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args:
    - --markdown-linebreak-ext=md
# Black (uncompromising) Python code formatter
#- repo: https://github.com/psf/black
#  rev: 22.6.0
#  hooks:
#  - id: black
#    args:
#    - --target-version
#    - py310
# MyPy
#- repo: https://github.com/pre-commit/mirrors-mypy
#  rev: v1.3.0
#  hooks:
#  - id: mypy
#    files: ^xchemalign
# Pylint
# To check import errors we need to install every package
# used by the DM. This is often impractical on the client,
# and so we disable import errors on pre-commit and rely
# on this category of test in the CI stage. Consequently,
# pylint may pass on pre-commit but fail in CI - but at least
# the user has done 90% of the lint checks before the code
# hits the server.
- repo: https://github.com/pycqa/pylint
  rev: v2.17.4
  hooks:
  - id: pylint
    args:
    - xchemalign
