target_name: Mpro
base_dir: data/inputs
output_dir: data/outputs/Mpro
copy_dir: data/inputs/copied
inputs:
  - dir: dls/labxchem/data/2020/lb18145-153
    soakdb: processing/database/soakDBDataFile.sqlite
    panddas_event_files:
      - processing/analysis/pandda_2_2020_04_25/analyses/pandda_inspect_events.csv
      - processing/analysis/pandda_2_2020_04_30/analyses/pandda_inspect_events.csv
      - processing/analysis/pandda_2_2020_05_10/analyses/pandda_inspect_events.csv

overrides:
  deprecations:
    Mpro-x0104: Cat did a wee on the crystal
    Mpro-x0165: Bad karma
  assemblies: assemblies.yaml
  xtal_forms: xtal_forms.yaml
  commands:
    - type: site_merge
      sites:
        - canonical
        - binding_pocket_1
        - allosteric
