target_name: Mpro
base_dir: data/inputs
input_dirs:
- /dls/labxchem/data/2020/lb18145-153
#- /dls/labxchem/data/2020/lb18145-158

inputs:
- dir: /dls/labxchem/data/2020/lb18145-153/processing/analysis/model_building
  soakbd: /dls/labxchem/data/2020/lb18145-153/processing/database/soakDBDatafile.sqlite
  panddas:
  - /dls/labxchem/data/2020/lb18145-153/processing/analysis/pandda_2_2020_04_30/analyses/pandda_inspect_events.csv
  - /dls/labxchem/data/2020/lb18145-153/processing/analysis/pandda_2_2020_04_25/analyses/pandda_inspect_events.csv
  - /dls/labxchem/data/2020/lb18145-153/processing/analysis/pandda_2_2020_05_10/analyses/pandda_inspect_events.csv

output_dir: data/outputs/Mpro

overrides:
  deprecations:
    Mpro-x0104: Cat did a wee on the crystal
    Mpro-x0165: Bad karma
  assemblies: assemblies.yaml
  xtal_forms: xtal_forms.yaml
  commands:
  - type: site_merge
    sites:
    - canonical
    - binding_pocket_1
    - allosteric

