target_name: Mpro
base_dir: data/inputs
output_dir: data/outputs/Mpro
ref_datasets:
- 5rgs
- 8dz9
- 8e1y

inputs:

# 10 PDB files
- dir: dls/science/groups/i04-1/conor_dev/xchemalign/mpro_pdb
  type: manual

# 4 Mpro_Nterm-* files
- dir: dls/labxchem/data/2020/lb27963-4
  type: model_building
  soakbd: processing/database/soakDBDataFile.sqlite
  panddas_event_files:
  - processing/analysis/panddas_20012021/analyses/pandda_inspect_events.csv

# 3 Mpro-IBM* files
- dir: dls/labxchem/data/2020/lb27995-1
  type: model_building
  soakbd: processing/database/soakDBDataFile.sqlite
  panddas_event_files:
  - processing/analysis/panddas/analyses/pandda_inspect_events.csv

# 14 Mpro-J00* files
- dir: dls/labxchem/data/2021/lb29612-3
  type: model_building
  soakbd: processing/database/soakDBDataFile.sqlite
  panddas_event_files:
  - processing/analysis/panddas/pandda_20210716/analyses/pandda_inspect_events.csv

#overrides:
#  deprecations:
#    Mpro-x0104: Cat did a wee on the crystal
#    Mpro-x0165: Bad karma
